apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-backend-deployment
  namespace: backstage
  labels:
    application: backstage
    component: backstage-backend
    environment: poc
    team: breu
spec:
  replicas: 3
  selector:
    matchLabels:
      application: backstage
      component: backstage-backend
      environment: poc
      team: breu
  template:
    metadata:
      labels:
        application: backstage
        component: backstage-backend
        environment: poc
        team: breu
    spec:
      serviceAccountName: backstage-workload-identity-55f14ee8
      imagePullSecrets:
        - name: docker
      containers:
        - name: backstage-backend
          image: europe-west3-docker.pkg.dev/hd-backstage-poc-28107/backstage-55f14ee8/backstage/backend:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 7007
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 7007
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
            timeoutSeconds: 15
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
          ports:
            -  containerPort: 7007
          env:
            - name: BACKSTAGE_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backstage-database-credentials-55f14ee8
                  key: db_host
            - name: BACKSTAGE_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: backstage-database-credentials-55f14ee8
                  key: db_port
            - name: BACKSTAGE_DB_USER
              valueFrom:
                secretKeyRef:
                  name: backstage-database-credentials-55f14ee8
                  key: db_user
            - name: BACKSTAGE_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: backstage-database-credentials-55f14ee8
                  key: db_pass
