apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-backend-deployment
  namespace: backstage
  labels:
    application: backstage
    component: backend
    environment: poc
    team: breu
spec:
  replicas: 3
  selector:
    matchLabels:
      application: backstage
      component: backend
      environment: poc
      team: breu
  template:
    metadata:
      labels:
        application: backstage
        component: backend
        environment: poc
        team: breu
    spec:
      serviceAccountName: backstage-workload-identity-55f14ee8
      imagePullSecrets:
        - name: docker
      containers:
        - name: backstage-backend
          image: europe-west3-docker.pkg.dev/hd-backstage-poc-28107/backstage-55f14ee8/backstage/backend:latest
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 7007
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
            timeoutSeconds: 15
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 7007
            initialDelaySeconds: 60
            periodSeconds: 15
            failureThreshold: 5
            timeoutSeconds: 15
          resources:
            requests:
              cpu: "128m"
              memory: "256Mi"
            limits:
              cpu: "192m"
              memory: "256Mi"
          ports:
            -  containerPort: 7007
          volumeMounts:
            - name: secrets
              mountPath: /etc/backstage/secrets
              readOnly: true
          env:
            - name: BACKSTAGE_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: backstage-application-credentials-55f14ee8
                  key: db_host
            - name: BACKSTAGE_DB_PORT
              valueFrom:
                secretKeyRef:
                  name: backstage-application-credentials-55f14ee8
                  key: db_port
            - name: BACKSTAGE_DB_USER
              valueFrom:
                secretKeyRef:
                  name: backstage-application-credentials-55f14ee8
                  key: db_user
            - name: BACKSTAGE_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: backstage-application-credentials-55f14ee8
                  key: db_pass
            - name: BACKSTAGE_APP_URL
              valueFrom:
                secretKeyRef:
                  name: backstage-application-credentials-55f14ee8
                  key: app_url
            - name: BACKSTAGE_BACKEND_URL
              valueFrom:
                secretKeyRef:
                  name: backstage-application-credentials-55f14ee8
                  key: backend_url
            - name: GITLAB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: backstage-application-credentials-55f14ee8
                  key: gitlab_token
            - name: GITLAB_DISCOVERY_URL
              valueFrom:
                secretKeyRef:
                  name: backstage-application-credentials-55f14ee8
                  key: gitlab_discovery_url
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/backstage/secrets/service_account.json
      volumes:
        - name: secrets
          secret:
            secretName: backstage-application-credentials-55f14ee8
            items:
            - key: service_account_json
              path: service_account.json
